/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.InternalFrames;

import Backend.Controllers.PnlSistemaVentasController;
import Backend.Controllers.PnlVentasController;
import Panels.Ventas.PnlSistemaVentas;
import Panels.Ventas.PnlVentas;
import java.awt.BorderLayout;

/**
 *
 * @author FAMILIASOZAORTIZ
 */
public class JifVentas extends javax.swing.JInternalFrame {
    private PnlVentas ventas;
    private PnlSistemaVentasController sistemaVentas;
    private PnlVentasController Controller;
    /**
     * Creates new form JifVentas
     */
    public JifVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ventas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ventas1.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 450));
        setRequestFocusEnabled(false);

        pnlContent.setPreferredSize(new java.awt.Dimension(700, 700));
        pnlContent.setLayout(new java.awt.BorderLayout());

        ventas= new PnlVentas();
        Controller= new PnlVentasController(ventas);
        pnlContent.add(ventas,BorderLayout.CENTER);

        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
