/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels.Compra;

/**
 *
 * @author FAMILIASOZAORTIZ
 */
public class PnlData extends javax.swing.JPanel {

    /**
     * Creates new form PnlData
     */
    public PnlData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDataCompra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlImageCompra = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        pnlDataCompra.setPreferredSize(new java.awt.Dimension(370, 400));
        pnlDataCompra.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("jLabel1");
        pnlDataCompra.add(jLabel1, new java.awt.GridBagConstraints());

        jLabel2.setText("jLabel2");
        pnlDataCompra.add(jLabel2, new java.awt.GridBagConstraints());

        jLabel3.setText("jLabel3");
        pnlDataCompra.add(jLabel3, new java.awt.GridBagConstraints());

        add(pnlDataCompra, java.awt.BorderLayout.LINE_START);

        pnlImageCompra.setLayout(new java.awt.GridBagLayout());

        lblImage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblImage.setText("No image");
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlImageCompra.add(lblImage, new java.awt.GridBagConstraints());

        add(pnlImageCompra, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblImage;
    private javax.swing.JPanel pnlDataCompra;
    private javax.swing.JPanel pnlImageCompra;
    // End of variables declaration//GEN-END:variables
}
